/*
 * tabbedPanel.java
 *
 * Created on Среда, 2006, Мај 3, 13.27
 */

package org.VIVE.gui.toolPanels;

import java.util.Hashtable;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.netbeans.swing.tabcontrol.TabData;
import org.netbeans.swing.tabcontrol.TabbedContainer;

/**
 *
 * @author  nikola
 */

public class tabbedPanel extends javax.swing.JPanel {
    
    private Hashtable contextPanels = new Hashtable();
    private TabbedContainer tab;
    private boolean toolActive = false;
    
    /** Creates new form tabbedPanel */
    public tabbedPanel() 
    {
        initComponents();
        tab = new TabbedContainer(TabbedContainer.TYPE_EDITOR);
        tab.setSize(200,300);
        tab.setVisible(true);
        this.add(tab);
    }
    
    public void setToolActive (boolean b)
    {
        toolActive = b;
    }
    
    public boolean getToolActive ()
    {
        return toolActive;
    }
    
    public void addTab (String name, JPanel panel)
    {
        TabData tData = new TabData(panel,null,name,null);
        contextPanels.put(tData,tData);
        tab.getModel().addTab(0,tData);
        tab.setActive(toolActive); //ubacuje prelaz boje kada se klikne na tab
        tab.getSelectionModel().setSelectedIndex(0);
    }
    
    public void setTab (String name, JPanel panel)
    {
        TabData tData = new TabData(panel,null,name,null);
        TabData oldPanel = (TabData)contextPanels.get(name);
        int oldNo = tab.getModel().indexOf(oldPanel);
        contextPanels.remove(name);
        tab.getModel().addTab(oldNo,tData);
        contextPanels.put(name,tData);
        
    }
    
    public JPanel getTabPanel (String name)
    {
        TabData tmp = (TabData) contextPanels.get(name);
        return (JPanel) tmp.getComponent();
    }
    
    public void removeTab(String name)
    {
        contextPanels.remove(name);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
   
    public static void main (String [] arg)
    {
        JFrame tmp = new JFrame();
        tmp.setSize(400,400);
        tmp.setVisible(true);
        tabbedPanel fr = new tabbedPanel();
        fr.setVisible(true);
        tmp.getContentPane().add(fr);
        tmp.repaint();
        fr.addTab("Drugi", new JPanel());
    }
}
