/*
 * toolPanel.java
 *
 * Created on Четвртак, 2006, Април 27, 14.33
 */

package org.VIVE.gui.toolPanels;

import javax.swing.JFrame;

/**
 *
 * @author  nikola
 */
public class toolPanelSlicer extends javax.swing.JPanel {
    
    /** Creates new form toolPanel */
    
    public toolPanelSlicer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Active = new javax.swing.JCheckBox();
        DragFramed = new javax.swing.JCheckBox();

        Active.setSelected(true);
        Active.setText("Active");
        Active.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Active.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActiveActionPerformed(evt);
            }
        });

        DragFramed.setSelected(true);
        DragFramed.setText("Drag Framed");
        DragFramed.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        DragFramed.setMargin(new java.awt.Insets(0, 0, 0, 0));
        DragFramed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DragFramedActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Active)
                    .add(DragFramed))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(Active)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(DragFramed)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActiveActionPerformed
// TODO add your handling code here:
        if (Active.isSelected()){
            
        } else {
            
        }
    }//GEN-LAST:event_ActiveActionPerformed

    private void DragFramedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DragFramedActionPerformed
// TODO add your handling code here:
        if (DragFramed.isSelected()){
            
        } else {
            
        }
    }//GEN-LAST:event_DragFramedActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Active;
    private javax.swing.JCheckBox DragFramed;
    // End of variables declaration//GEN-END:variables
    
    public static void main (String[] a){
        JFrame tmp = new JFrame();
        tmp.setSize(400,200);
        
        toolPanelSlicer TPS = new toolPanelSlicer();
        //v.setSize(200,200);
        tmp.getContentPane().add(TPS).setBounds(0,0,200,200);
        tmp.setVisible(true);
        tmp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
}
