/*
 * Navigation.java
 *
 * Created on Понедељак, 2006, Јуни 19, 10.08
 */

package org.VIVE.gui.toolOperators;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import org.VIVE.gui.toolOperators.interfaces.NavigationConstants;
import org.VIVE.gui.toolOperators.interfaces.iNavigation;
import java.util.Hashtable;

/**
 *
 * @author  nikola
 */
public class Navigation extends javax.swing.JPanel implements NavigationConstants, ActionListener {
    

    private iNavigation alat;
    private Hashtable StringToInteger = new Hashtable();
    
    /** Creates new form Navigation */
    private Navigation() {
        initComponents();
    }
    
    public Navigation(int andOpp, iNavigation tool)
    {
        initComponents();
        RegisterActionListeners();
        if ((andOpp&KRETANJE)!=KRETANJE) panelKretanje.setVisible(false);
        if ((andOpp&AKCIJE)!=AKCIJE) panelAkcije.setVisible(false);
        if ((andOpp&FIT)!=FIT) panelFit.setVisible(false);
        alat = tool;
        this.PopulateHash();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelKretanje = new javax.swing.JPanel();
        btnDown = new javax.swing.JButton();
        btnBackward = new javax.swing.JButton();
        btnForward = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        panelAkcije = new javax.swing.JPanel();
        btnRotation = new javax.swing.JButton();
        btnSize = new javax.swing.JButton();
        btnPosition = new javax.swing.JButton();
        panelFit = new javax.swing.JPanel();
        btnFit = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelKretanje.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDown.setText("Down");

        btnBackward.setText("Backward");

        btnForward.setText("Forward");

        btnUp.setText("Up");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnLeft.setText("Left");

        btnRight.setText("Right");

        org.jdesktop.layout.GroupLayout panelKretanjeLayout = new org.jdesktop.layout.GroupLayout(panelKretanje);
        panelKretanje.setLayout(panelKretanjeLayout);
        panelKretanjeLayout.setHorizontalGroup(
            panelKretanjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelKretanjeLayout.createSequentialGroup()
                .addContainerGap()
                .add(btnLeft)
                .add(10, 10, 10)
                .add(panelKretanjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, btnDown, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, btnUp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, btnForward, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, btnBackward, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnRight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelKretanjeLayout.setVerticalGroup(
            panelKretanjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelKretanjeLayout.createSequentialGroup()
                .addContainerGap()
                .add(btnUp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(panelKretanjeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnRight)
                    .add(btnLeft)
                    .add(btnForward, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnBackward, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnDown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAkcije.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRotation.setText("Rotation");
        btnRotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotationActionPerformed(evt);
            }
        });

        btnSize.setText("Size");
        btnSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeActionPerformed(evt);
            }
        });

        btnPosition.setText("Position");
        btnPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPositionActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelAkcijeLayout = new org.jdesktop.layout.GroupLayout(panelAkcije);
        panelAkcije.setLayout(panelAkcijeLayout);
        panelAkcijeLayout.setHorizontalGroup(
            panelAkcijeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelAkcijeLayout.createSequentialGroup()
                .addContainerGap()
                .add(btnPosition)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnSize, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnRotation)
                .addContainerGap())
        );
        panelAkcijeLayout.setVerticalGroup(
            panelAkcijeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelAkcijeLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(panelAkcijeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnPosition)
                    .add(btnRotation)
                    .add(btnSize))
                .addContainerGap())
        );

        panelFit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelFit.setAutoscrolls(true);
        btnFit.setText("Fit");
        btnFit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelFitLayout = new org.jdesktop.layout.GroupLayout(panelFit);
        panelFit.setLayout(panelFitLayout);
        panelFitLayout.setHorizontalGroup(
            panelFitLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelFitLayout.createSequentialGroup()
                .add(58, 58, 58)
                .add(btnFit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .add(80, 80, 80))
        );
        panelFitLayout.setVerticalGroup(
            panelFitLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelFitLayout.createSequentialGroup()
                .addContainerGap()
                .add(btnFit)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelFit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelAkcije, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelKretanje, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panelKretanje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelAkcije, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelFit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotationActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_btnRotationActionPerformed

    private void btnPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositionActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_btnPositionActionPerformed

    private void btnSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeActionPerformed
        alat.setInitSize();   
    }//GEN-LAST:event_btnSizeActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
           
            
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnFitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFitActionPerformed
        if (evt.getActionCommand().equalsIgnoreCase("Fit"))
        {
            btnFit.setText("Previous Scale");
        } else 
        {
            btnFit.setText("Fit");
        }
        //plus add code which does something to this method   (   not yet implemented:  fitToVW()   )
    }//GEN-LAST:event_btnFitActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackward;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnFit;
    private javax.swing.JButton btnForward;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnPosition;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnRotation;
    private javax.swing.JButton btnSize;
    private javax.swing.JButton btnUp;
    private javax.swing.JPanel panelAkcije;
    private javax.swing.JPanel panelFit;
    private javax.swing.JPanel panelKretanje;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        int tmp = ((Integer)StringToInteger.get(e.getActionCommand())).intValue();
        
        // Treba proceniti kojoj grupi pripada pa onda pozvati odgovarajucu
        // metodu iNavigation interfejsa
        System.out.println("Sad smo u glavnom action performed-u Navigation-a");
        if (tmp>=10&&tmp<20)
        {
            //Move akcija
            alat.moveTool(tmp);
        }
        else if (tmp>=20&&tmp<30)
        {
             //Akcija
             alat.setPositionSizeRotation(tmp);
        }
        else 
        {
            //Fit
            alat.setScale(tmp);
        }
        
    }
    
    private void PopulateHash(){
        //Ovo moze dinamicki u zavisnosti NavigationConstants interfejsa
        StringToInteger.put("Up",new Integer(this.UP));
        StringToInteger.put("Down",new Integer(this.DOWN));
        StringToInteger.put("Left",new Integer(this.LEFT));
        StringToInteger.put("Right",new Integer(this.RIGHT));
        StringToInteger.put("Forward",new Integer(this.FORWARD));
        StringToInteger.put("Backward",new Integer(this.BACKWARD));
        
        StringToInteger.put("Position",new Integer(this.POSITION));
        StringToInteger.put("Size",new Integer(this.SIZE));
        StringToInteger.put("Rotation",new Integer(this.ROTATION));
        
        StringToInteger.put("Fit",new Integer(this.FitToVolume));
        StringToInteger.put("Previous Scale", new Integer(this.PreviousScale));
    }
    private void RegisterActionListeners(){
        btnUp.addActionListener(this);
        btnDown.addActionListener(this);
        btnForward.addActionListener(this);
        btnBackward.addActionListener(this);
        btnLeft.addActionListener(this);
        btnRight.addActionListener(this);
        btnPosition.addActionListener(this);
        btnSize.addActionListener(this);
        btnRotation.addActionListener(this);
        
        btnFit.addActionListener(this);
    }
   
    /**
    * Za potrebe testiranja
    * 
    */
    public static void main (String[] a){
        JFrame tmp = new JFrame();
        tmp.setSize(300,400);
        Navigation n = new Navigation(Navigation.FIT|Navigation.KRETANJE|Navigation.AKCIJE, null);
        //v.setSize(200,200);
        tmp.getContentPane().add(n).setBounds(0,0,300,400);
        tmp.setVisible(true);
        tmp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
}
