/*
 * Visibility1.java
 *
 * Created on Понедељак, 2006, Јуни 19, 9.33
 */

package org.VIVE.gui.toolOperators;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Hashtable;
import javax.swing.JRadioButton;
import org.VIVE.gui.toolOperators.interfaces.iVisibility;

/**
 * U zavisnosti parametara prosledjenih konstruktorom, svasta se desava...
 * @author  nikola
 */
public class Visibility extends javax.swing.JPanel implements ActionListener {
    
    /** Creates new form Visibility1 */
    private JRadioButton [] aButtons;
    private javax.swing.ButtonGroup buttonGroup1;
    private iVisibility alat;
    private Hashtable Tabela = new Hashtable();
    private Hashtable Tabela2 = new Hashtable();
    
    private Visibility() {
        initComponents();
    }
    
    //public Visibility(String[] nivoi, iVisibility tool){
    public Visibility(VisibilityComponent[] nivoi, iVisibility tool){
        alat = tool;
        //Dinamicki pravi dugmice
        buttonGroup1 = new javax.swing.ButtonGroup();
        aButtons = new JRadioButton[nivoi.length];
        setLayout(new GridLayout(nivoi.length,0));
        for (int i=0;i<nivoi.length;i++)
        {
            aButtons[i] = new JRadioButton();
            aButtons[i].addActionListener(this);
            aButtons[i].setText(nivoi[i].getName());
            Tabela.put(nivoi[i].getName(),new Integer(nivoi[i].getID()));
            Tabela.put(new Integer(nivoi[i].getID()),nivoi[i].getName());
            aButtons[i].setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            aButtons[i].setMargin(new java.awt.Insets(0, 0, 0, 0));
            this.add(aButtons[i]);
            buttonGroup1.add(aButtons[i]);
            //if (i==select) aButtons[i].setSelected(true);
        }
        //initComponents();
        // prema broju komponenti da dobija maximalne dimenzije
         this.setSize(200,30*(nivoi.length+1));
        this.setVisible(true);
        //TODO: treba da se selektuje neki od dugmica
    }
    
    public Visibility(String[] nivoi, iVisibility tool){
        alat = tool;
        //Dinamicki pravi dugmice
        buttonGroup1 = new javax.swing.ButtonGroup();
        aButtons = new JRadioButton[nivoi.length];
        setLayout(new GridLayout(nivoi.length,0));
        for (int i=0;i<nivoi.length;i++){
            aButtons[i] = new JRadioButton();
            aButtons[i].addActionListener(this);
            aButtons[i].setText(nivoi[i]);
            Tabela.put(nivoi[i],new Integer(i));
            Tabela.put(new Integer(i),nivoi[i]);
            aButtons[i].setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            aButtons[i].setMargin(new java.awt.Insets(0, 0, 0, 0));
            this.add(aButtons[i]);
            buttonGroup1.add(aButtons[i]);
            //if (i==select) aButtons[i].setSelected(true);
        }
        //initComponents();
        // prema broju komponenti da dobija maximalne dimenzije
         this.setSize(200,30*(nivoi.length+1));
        this.setVisible(true);
        //TODO: treba da se selektuje neki od dugmica
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 213, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    

    public void actionPerformed(ActionEvent e) 
    {
        for (int i=0; i<aButtons.length;i++)
        {
            if (aButtons[i].getText().compareTo(e.getActionCommand())==0)
            {
                Integer tmp = (Integer)Tabela.get(e.getActionCommand());
                alat.setVisibilityLevel(tmp.intValue());
            }
        }
    }
    
    public void setVisibilityLevel(int level)
    {
        String tmp=(String) Tabela.get(new Integer(level));
        for (int i =0; i< aButtons.length;i++)
        {
            if (aButtons[i]!=null)
            if (aButtons[i].getText().equalsIgnoreCase(tmp))
            {
                aButtons[i].setSelected(true);
                break;
            }
        }
        
    }
    
    /**
    * Za potrebe testiranja
    * 
    */
     /*public static void main (String[] a){
        JFrame tmp = new JFrame();
        tmp.setSize(400,200);
        String[] s = new String[3];
        s[0] = "Prva opcija";
        s[1] = "Druga opcija";
        s[2] = "Nijedna vise";
        Visibility v = new Visibility(s,null);
        //v.setSize(200,200);
        tmp.getContentPane().add(v).setBounds(0,0,200,200);
        tmp.setVisible(true);
        tmp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }*/
}
